language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
  - composer update --prefer-dist
script:
  # - php ./vendor/phpunit/phpunit/phpunit
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php ./vendor/bin/coveralls -v
notifications:
  email:
    - dev@dankempster.co.uk
matrix:
  allow_failures:
    - php: hhvm
branches:
  only:
    - develop
    - master
